base_url = "https://lm4uc.github.io"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme, which is [designed to last](https://jeffhuang.com/designed_to_last/)."
banner = {extension = "svg", size = "fixed", fade = true}
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"}]